### ISSUE TITLE
Choose a different license for the source code

### ISSUE THREAD

**Issue by leonard84** [obfuscoder/flee_rails#77]
> Can I apply a Creative Commons license to software?

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

> While we recommend against using a CC license on software itself, CC licenses may be used for software documentation, as well as for separate artistic elements such as game art or music.

https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_use_a_Creative_Commons_license_for_software.3F

**Comment by obfuscoder** [comment]
True, CC is not touching on providing source code. However this is not my concern as I chose the BY-NC-ND license, hence it is not allowed to modify or make a derivative of the project. Due to the attribution terms there shall always be a link to the origin and thus the source is available again.

Unfortunately, other open source licenses (like AGPL which I considered as well) do not forbid commercial use so I would need to dual-license the project in this case. As I am not a lawyer or unwilling to invest in creating a commercial license at the moment, I stick with the BY-NC-ND.
